apiVersion: v1
kind: Service
metadata:
  labels:
    app: interest-payout
    environment: Development
  name: interest-payout
  namespace: lykke
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 5000
  - name: grpc
    port: 80
    protocol: TCP
    targetPort: 5001
  selector:
    app: interest-payout
  sessionAffinity: None
  type: ClusterIP
