name: CI dev build

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - reopened
      - synchronize

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Raise deploy to dev flag
      id: Raise_deploy_to_dev_flag
      run: |
        echo "SHOULD_DEPLOY_TO_DEV=true" >> $GITHUB_ENV   
      if: contains( github.event.pull_request.labels.*.name, 'dev' ) || startsWith(github.ref, 'refs/heads/dev-') || github.ref=='refs/heads/master'
    - name: Build
      run: dotnet build --configuration Release /p:AssemblyVersion=0.0.0
    - name: Test
      run: dotnet test --no-build --configuration Release
